### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by maxfmachado** [maxfmachado/projeto-pacote-turistico#1]
**Classes**
- [x] Cidade (0,3 ponto)
- [x] Construtor para já iniciar os valores dos atributos internos da classe já no momento da criação da instância (0,3 ponto)
- [ ] Não permitir o cadastro duplicado de hotéis e restaurantes na cidade (0,4 ponto)
- [x] Usar um enumerador no tipo do atributo referente a UF da cidade (0,2 ponto)

- [x] Hotel (0,3 ponto)
- [x] Construtor para já iniciar os valores dos atributos internos da classe já no momento da criação da instância (0,3 ponto)
- [x] PacoteTuristico (0,3 ponto)
- [x] Construtor para já iniciar os valores dos atributos internos da classe já no momento da criação da instância (0,3 ponto)
- [ ] Método estático para criação de nova instância (0,3 ponto)
- [x] Restaurante (0,3 ponto)
- [ ] Construtor para já iniciar os valores dos atributos internos da classe já no momento da criação da instância (0,3 ponto)
- [x] BancoDeDadosFake

**Métodos**
- [x] AddCidade (0,3 ponto)
- [ ] Impedir cadastro duplicado (0,4 ponto)
- [x] AddHotel (0,3 ponto)
- [ ] Impedir cadastro duplicado (0,4 ponto)
- [x] AddRestaurante (0,3 ponto)
- [ ] Impedir cadastro duplicado (0,4 ponto)
- [x] Uso de herança (0,45 ponto)

**Classe Main**
- [ ] Classe e/ou métodos para captura das informações do usuário de forma que se minimize a redundância de códigos (refatoração) (0,45 ponto)
Viabilizar a execução dos códigos que no momento não estão codificados nem funcionando.
- [x] linha 28 » bd.GetCidadePeloId(idEscolhido) (0,45 ponto)
- [x] linha 40 » cidadeEscolhida.GetHoteis() (0,45 ponto)
- [x] linha 45 » bd.GetHotelPeloId(idEscolhido) (0,45 ponto)
- [x] linha 88 » cidadeEscolhida.GetRestaurantes() (0,45 ponto)
- [x] linha 93 » bd.GetRestaurantePeloId(idEscolhido) (0,45 ponto)
- [x] linha 107 » PacoteTuristico.Novo(cidadeEscolhida, hotelEscolhido, dataIniPacote, qtdDias, restauranteEscolhido, qtdRefeicoes); (0,45 ponto)
